### ISSUE TITLE
Missing Node: Add Subscribers to Lists

### ISSUE THREAD

**Issue by anantanandgupta** [LucasSovre/listmonk-n8n#4]
Dear @LucasSovre, as I am actively following this repo, I realized that you have a new code of conduct for the PRs, so here I am opening a feature request.

the feature in question is the capability of Listmonk to add one or more subscribers to one or more lists. There is an api endpoint available from Listmonk as documented [here](https://listmonk.app/docs/apis/subscribers/#put-apisubscriberslists). This feature is missing in this module.

I will quickly work on the feature and create a PR.

**Comment by LucasSovre** [comment]
Thanks, for creating an issue, if the improvement ask is legitimate, we will work on it as soon as possible, do not hesitate to create your own pull-request 😉

**Comment by LucasSovre** [comment]
> Dear @LucasSovre, as I am actively following this repo, I realized that you have a new code of conduct for the PRs, so here I am opening a feature request.
> 
> the feature in question is the capability of Listmonk to add one or more subscribers to one or more lists. There is an api endpoint available from Listmonk as documented [here](https://listmonk.app/docs/apis/subscribers/#put-apisubscriberslists). This feature is missing in this module.
> 
> I will quickly work on the feature and create a PR.

Amazing, do not hesitate to tag me on the PR and I will review it as soon as possible

**Comment by anantanandgupta** [comment]
@LucasSovre ... here you go :)

**Comment by LucasSovre** [comment]
merged and published to npm package with https://github.com/LucasSovre/listmonk-n8n/releases/tag/1.0.6

**Comment by LucasSovre** [comment]
merged and published to npm package with https://github.com/LucasSovre/listmonk-n8n/releases/tag/1.0.6
